source 'https://rubygems.org'

gem 'rails', __RAILS_VERSION__
gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

# Use Puma as the app server
gem 'puma'

# Use ActiveModelSerializers to serialize JSON responses
gem 'active_model_serializers', '~> 0.10.0.rc1'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

# Seamless JWT authentication for Rails API
gem 'knock', '~> 1.2'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

# Add some fanciness to minitest
gem 'minitest-reporters', group: :test

# To use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Heroku in production
# gem 'rails_12factor', group: :production

# Use Code Climate
# gem "codeclimate-test-reporter", group: :test, require: nil

# Use Delayed Job as ActiveJob backend
# gem 'daemons'
# gem 'delayed_job_active_record'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
